### ISSUE TITLE
还是不行，总是英文的

### ISSUE THREAD

**Issue by weituotian** [wang12124468/monaco-editor-esm-webpack-plugin#1]
![image](https://user-images.githubusercontent.com/7270968/70287682-cca00480-180a-11ea-954e-06c917a3fb3e.png)

![image](https://user-images.githubusercontent.com/7270968/70287663-bf831580-180a-11ea-980f-c4bdef7c00e2.png)

包确保只有一个了
![image](https://user-images.githubusercontent.com/7270968/70287636-a712fb00-180a-11ea-8a74-38694eb57a99.png)

**Comment by wang12124468** [comment]
你应该先设置国际化，再加载monaco，因为在加载monaco的是就会去加载语言

**Comment by wang12124468** [comment]
I'm sorry. 我写的demo错了，已经修正了
