### ISSUE TITLE
Cannot read property 'original' of undefined

### ISSUE THREAD

**Issue by yinyoude** [wang12124468/monaco-editor-esm-webpack-plugin#12]
点击鼠标右键的时候，生成菜单错误
When clicking the right mouse button, a menu error is generated
![image](https://user-images.githubusercontent.com/39619762/113684818-2ca50480-96f8-11eb-9667-49b163c3739d.png)
我使用的是 vue-cli3，配置如下
I am using vue-cli3, the configuration is as follows
![image](https://user-images.githubusercontent.com/39619762/113684940-4f371d80-96f8-11eb-9726-dd779c21b4fd.png)
![image](https://user-images.githubusercontent.com/39619762/113684965-578f5880-96f8-11eb-8fe0-c711dea279a4.png)

**Comment by wang12124468** [comment]
It seems your monaco-editor had some errors. You can remove `monaco-editor-esm-webpack-plugin` and test the contextMenu

**Comment by Dodobibi** [comment]
I have same issue.

contexstMenu work nice without `monaco-editor-esm-webpack-plugin`

**Comment by Baloneo** [comment]
> I have same issue.
> 
> contexstMenu work nice without `monaco-editor-esm-webpack-plugin`
> 
> **EDIT**
> 
> Finally, I'v omitted `rules` in webpack conf :
> 
> ```js
> rules: [
>   {
>     test: /\.js/,
>     enforce: 'pre',
>     include: /[\\\/]monaco-editor[\\\/]esm/,
>     use: MonacoWebpackPlugin.loader,
>   },
> ],
> plugins: [
>   new MonacoWebpackPlugin({
>     /**options*/
>   }),
> ],
> ```
> 
> All working nice now.

Is there a complete configuration code?

**Comment by yar2001** [comment]
> I have same issue.
> 
> contexstMenu work nice without `monaco-editor-esm-webpack-plugin`
> 
> **EDIT**
> 
> Finally, I'v omitted `rules` in webpack conf :
> 
> ```js
> rules: [
>   {
>     test: /\.js/,
>     enforce: 'pre',
>     include: /[\\\/]monaco-editor[\\\/]esm/,
>     use: MonacoWebpackPlugin.loader,
>   },
> ],
> plugins: [
>   new MonacoWebpackPlugin({
>     /**options*/
>   }),
> ],
> ```
> 
> All working nice now.

好样的，我用React+craco，用你的方法也可以了
Great, I am using React+craco, and it works in your way

**Comment by xueerli** [comment]
@yinyoude 你是怎么解决的？我去掉了webpack rules一样报这个错误

**Comment by xueerli** [comment]
@byte-voyager @yar2001 
Hi, Why omit rules?
