### ISSUE TITLE
右键菜单只能部分汉化，不能全部汉化

### ISSUE THREAD

**Issue by apricotJune** [wang12124468/monaco-editor-esm-webpack-plugin#21]
按照npm中的使用教程配置好vue.config.js以及在使用moncao的文件设置了本地数据后，只能部分汉化右键菜单
如下图：
![image](https://user-images.githubusercontent.com/107164329/223338652-feeaaf59-2c80-4d2f-b085-dc387fecbd6b.png)
具体代码如下：
vue.config.js中
`
const MonacoWebpackPlugin = require("monaco-editor-esm-webpack-plugin")
plugins: [
      new MonacoWebpackPlugin(),
    ],
    module: {
      rules: [{
				test: /\.js/,
				enforce: 'pre',
				include: /node_modules[\\\/]monaco-editor[\\\/]esm/,
				use: MonacoWebpackPlugin.loader
      }]
    }
`

monaco.Editor.vue中

import { setLocaleData } from "monaco-editor-nls"
import zh_CN from "monaco-editor-nls/locale/zh-hans"
setLocaleData(zh_CN)

const monaco = require("monaco-editor/esm/vs/editor/editor.api"); 

monaco.editor.create(dom, {
language: "xml",
})

**Comment by wupeng-engineer** [comment]
试试这样 https://github.com/wupeng-engineer/monaco-editor-esm-nls-webpack-plugin

**Comment by wang12124468** [comment]
或者，你可以fork monaco-editor-nl，运行npm run create-locale 更新locales文件，然后本地依赖你fork的项目

**Comment by wang12124468** [comment]
两种可能：

1.  你有地方引用了monaco 下部分文件，在setLocaleData之前
2. 当前locales文件不是最新的，你可以使用文档中另一种模式，使用和monaco一致的locales文件： https://github.com/wang12124468/monaco-editor-nls#using-custom-locale
