### ISSUE TITLE
A suggestion about README

### ISSUE THREAD

**Issue by minecraftfen** [wang12124468/monaco-editor-esm-webpack-plugin#22]
I have been wasting a whole day embedding this plugin into my project just because I need to make two modifications in `webpack.config.js`, one is `plugin` and the other is `module.rules,` and I only modified `plugin`. I suggest modifying the `webpack.config.js` given in README, only shows the parts that need to be modified and not providing the entire config to avoid people working on it for a long time like me.

**Comment by wang12124468** [comment]
It only take ten minutes to configure this plugin when you have configured the monaco-editor.
