### ISSUE TITLE
monaco-editor-webpack-plugin版本升级的问题

### ISSUE THREAD

**Issue by tuxianchao** [wang12124468/monaco-editor-esm-webpack-plugin#3]
插件和编辑的版本好像需要升级下,如果我直接升级这个依赖的monaco-editor-webpack-plugin版本会产生额外的影响吗

https://github.com/Microsoft/monaco-editor-webpack-plugin#version-matrix

monaco-editor-webpack-plugin | monaco-editor
-- | --
2.*.* | 0.21.*
1.9.* | 0.20.*
1.8.* | 0.19.*
1.7.* | 0.18.*

**Comment by wang12124468** [comment]
1. `monaco-editor-esm-webpack-plugin` 不会影响其他（只要monaco-editor中的国际化底层方案未调整）
2. 如果要升级`monaco-editor`和`monaco-editor-webpack-plugin`，首先他们的版本需要对应，如果要使用本插件，你可以fork一下调整一下依赖关系，或者使用分支：feature-2.0.0（未测试）

**Comment by wang12124468** [comment]
`monaco-editor-esm-webpack-plugin` 仅仅是对部分文件进行替换

**Comment by tuxianchao** [comment]
行
